In [1]:
using Revise
using OnePiece

## compare_with_target

In [2]:
fu = "mean_difference"

"mean_difference"

In [3]:
n_ro = 2

n_co = 6

ma = OnePiece.tensor.simulate(n_ro, n_co)

2×6 Matrix{Float64}:
 1.0  3.0  5.0  7.0   9.0  11.0
 2.0  4.0  6.0  8.0  10.0  12.0

In [4]:
n_ze = convert(Int64, n_co / 2)

n_on = n_co - n_ze

bi = convert(BitVector, [zeros(n_ze); ones(n_on)])

6-element BitVector:
 0
 0
 0
 1
 1
 1

In [5]:
co = [10^(id - 1) for id in 1:n_co]

6-element Vector{Int64}:
      1
     10
    100
   1000
  10000
 100000

In [6]:
OnePiece.feature_x_sample.compare_with_target(co, ma, fu)

2-element Vector{Float64}:
 18512.5
 18511.5

In [7]:
OnePiece.feature_x_sample.compare_with_target(bi, ma, fu)

2-element Vector{Float64}:
 -6.0
 -6.0