In [9]:
using Revise
using OnePiece

## compare_with_target

In [10]:
n_ro = 5

n_co = 4

ma = OnePiece.tensor.simulate(n_ro, n_co)

5×4 Matrix{Float64}:
 1.0   6.0  11.0  16.0
 2.0   7.0  12.0  17.0
 3.0   8.0  13.0  18.0
 4.0   9.0  14.0  19.0
 5.0  10.0  15.0  20.0

In [11]:
n_ze = convert(Int64, n_co / 2)

n_on = n_co - n_ze

bi_ = convert(BitVector, [zeros(n_ze); ones(n_on)])

4-element BitVector:
 0
 0
 1
 1

In [12]:
ve = [10^(id - 1) for id in 1:n_co]

4-element Vector{Int64}:
    1
   10
  100
 1000

In [13]:
OnePiece.feature_x_sample.compare_with_target(bi_, ma, "signal_to_noise_ratio")

5-element Vector{Float64}:
 -1.414213562373095
 -1.414213562373095
 -1.414213562373095
 -1.414213562373095
 -1.414213562373095

In [14]:
OnePiece.feature_x_sample.compare_with_target(ve, ma, "signal_to_noise_ratio")

5-element Vector{Float64}:
 0.5494614395481072
 0.547420728537715
 0.5453800175273228
 0.5433393065169305
 0.5412985955065382