In [1]:
using OnePiece

using KernelDensity

## get_entropy

In [2]:
OnePiece.information.get_entropy(zeros(10))

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
OnePiece.information.get_entropy(ones(10))

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

## get_signal_to_noise_ratio

In [4]:
for (te1, te2) in [
    (collect(1:3), collect(10:10:30)),
    (zeros(3), zeros(3)),
    (ones(3), [0.001, 0.001, 0.001]),
    ([0.001, 0.001, 0.001], ones(3)),
    ([0.001, 0.001, 0.001], [10, 10, 10]),
]

    println(OnePiece.information.get_signal_to_noise_ratio(te1, te2))

end

-1.6363636363636365
0.0
4.990009990009989
-4.990009990009989
-4.999000099990002


## get_*

In [5]:
function call_all(te1, te2, te)

    vcat(
        [
            fu(te1, te2) for fu in [
                OnePiece.information.get_kolmogorov_smirnov_statistic,
                OnePiece.information.get_kullback_leibler_divergence,
                OnePiece.information.get_thermodynamic_breadth,
                OnePiece.information.get_thermodynamic_depth,
            ]
        ],
        [
            fu(te1, te2, te) for fu in [
                OnePiece.information.get_symmetric_kullback_leibler_divergence,
                OnePiece.information.get_antisymmetric_kullback_leibler_divergence,
            ]
        ],
    )

end

call_all (generic function with 1 method)

In [6]:
name_ = [
    "kolmogorov_smirnov_statistic",
    "kullback_leibler_divergence",
    "thermodynamic_breadth",
    "thermodynamic_depth",
    "symmetric_kullback_leibler_divergence",
    "antisymmetric_kullback_leibler_divergence",
]

6-element Vector{String}:
 "kolmogorov_smirnov_statistic"
 "kullback_leibler_divergence"
 "thermodynamic_breadth"
 "thermodynamic_depth"
 "symmetric_kullback_leibler_divergence"
 "antisymmetric_kullback_leibler_divergence"

In [7]:
for (te1, te2) in [([1, 1, 1], [1, 1, 1]), ([1, 2, 3], [10, 20, 30])]

    te = 0.2 * te1 + 0.8 * te2

    OnePiece.figure.plot_scatter([te1, te2])

    OnePiece.figure.plot_scatter(call_all(te1, te2, te); name_ = name_)

end

Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.48.613.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.49.722.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.49.732.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.49.744.html.


In [8]:
n_po = 100

te1 = OnePiece.vector_number.shift_minimum(randn(n_po), "0<")

ve1s = te1 .+ 1

te2 = OnePiece.vector_number.shift_minimum(randn(n_po), "0<")

100-element Vector{Float64}:
 0.5091773415303793
 2.992791176964663
 3.4698778209198373
 1.8412171615154471
 2.4938728760989926
 2.152196930060813
 3.1229860621393715
 1.108009250605363
 1.6561502401682626
 2.2868128787246684
 2.4298789025434555
 1.4489772843358277
 1.464294203765483
 ⋮
 2.7661720482509917
 3.3050065256068444
 4.380990688178485
 2.1533916037368797
 2.5790557529114335
 2.5482508594726068
 2.3696214979055035
 1.6406374211905659
 1.422323245710614
 2.8020534899619864
 2.1151937316004794
 2.3135923414975634

In [9]:
for (te1, te2) in [(te1, te1), (te1, ve1s), (te1, te2)]

    un1 = kde(te1)

    un2 = kde(te2)

    de1 = un1.density

    de2 = un2.density

    de3 = 0.2 * de1 + 0.8 * de2

    OnePiece.figure.plot_scatter(
        [de1, de2],
        [collect(un1.x), collect(un2.x)];
        layout = Dict("yaxis" => Dict("title" => "Density"), "xaxis" => Dict("title" => "Grid")),
    )

    OnePiece.figure.plot_scatter(call_all(de1, de2, de3); name_ = name_)

end

Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.51.637.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.52.18.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.52.205.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.52.258.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.52.273.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.52.29.html.


## get_mutual_information

## get_information_coefficient

In [10]:
te1 = collect(0:10)

te2 = collect(0:10:100)

bi = kde((te1, te2), npoints = (8, 8))

y = collect(bi.y)

x = collect(bi.x)

z = bi.density

OnePiece.figure.plot_heat_map(z, y, x)

Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.53.538.html.


"/var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_10.52.53.538.html"