In [1]:
using OnePiece

using KernelDensity

## get_entropy

In [2]:
OnePiece.information.get_entropy(zeros(10))

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [3]:
OnePiece.information.get_entropy(ones(10))

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

## get_signal_to_noise_ratio

In [4]:
for (te1, te2) in [
    (collect(1:3), collect(10:10:30)),
    (zeros(3), zeros(3)),
    (ones(3), [0.001, 0.001, 0.001]),
    ([0.001, 0.001, 0.001], ones(3)),
    ([0.001, 0.001, 0.001], [10, 10, 10]),
]

    println(OnePiece.information.get_signal_to_noise_ratio(te1, te2))

end

-1.6363636363636365
0.0
4.990009990009989
-4.990009990009989
-4.999000099990002


## get_*

In [5]:
function call_all(te1, te2, te)

    vcat(
        [
            fu(te1, te2) for fu in [
                OnePiece.information.get_kolmogorov_smirnov_statistic,
                OnePiece.information.get_kullback_leibler_divergence,
                OnePiece.information.get_thermodynamic_breadth,
                OnePiece.information.get_thermodynamic_depth,
            ]
        ],
        [
            fu(te1, te2, te) for fu in [
                OnePiece.information.get_symmetric_kullback_leibler_divergence,
                OnePiece.information.get_antisymmetric_kullback_leibler_divergence,
            ]
        ],
    )

end

call_all (generic function with 1 method)

In [6]:
name_ = [
    "kolmogorov_smirnov_statistic",
    "kullback_leibler_divergence",
    "thermodynamic_breadth",
    "thermodynamic_depth",
    "symmetric_kullback_leibler_divergence",
    "antisymmetric_kullback_leibler_divergence",
]

6-element Vector{String}:
 "kolmogorov_smirnov_statistic"
 "kullback_leibler_divergence"
 "thermodynamic_breadth"
 "thermodynamic_depth"
 "symmetric_kullback_leibler_divergence"
 "antisymmetric_kullback_leibler_divergence"

In [7]:
for (te1, te2) in [([1, 1, 1], [1, 1, 1]), ([1, 2, 3], [10, 20, 30])]

    te = 0.2 * te1 + 0.8 * te2

    OnePiece.figure.plot_scatter([te1, te2])

    OnePiece.figure.plot_scatter(call_all(te1, te2, te); name_ = name_)

end

Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.19.834.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.20.97.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.20.981.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.20.994.html.


In [8]:
n_po = 100

te1 = OnePiece.vector_number.shift_minimum(randn(n_po), "0<")

ve1s = te1 .+ 1

te2 = OnePiece.vector_number.shift_minimum(randn(n_po), "0<")

100-element Vector{Float64}:
 2.850132405437731
 2.1207637343982504
 3.744172136483672
 1.2274239777844573
 2.888583717272323
 2.3743594304883016
 3.4792746377657053
 4.174475746205022
 2.5323886494673222
 2.158892133202827
 1.8372491891046971
 2.7337504644560506
 2.4010263552659805
 ⋮
 1.676698201296944
 1.940171338382153
 2.156903545655193
 2.1833599979127754
 2.9375404598235533
 2.6345271769768455
 1.4948433525648952
 2.6576367733547874
 2.9991131861087506
 1.006497996650708
 3.13591168280567
 2.132074360624336

In [9]:
for (te1, te2) in [(te1, te1), (te1, ve1s), (te1, te2)]

    un1 = kde(te1)

    un2 = kde(te2)

    de1 = un1.density

    de2 = un2.density

    de3 = 0.2 * de1 + 0.8 * de2

    OnePiece.figure.plot_scatter(
        [de1, de2],
        [collect(un1.x), collect(un2.x)];
        layout = Dict("yaxis" => Dict("title" => "Density"), "xaxis" => Dict("title" => "Grid")),
    )

    OnePiece.figure.plot_scatter(call_all(de1, de2, de3); name_ = name_)

end

Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.22.931.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.23.492.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.23.518.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.23.565.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.23.58.html.
Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.23.598.html.


## get_mutual_information

## get_information_coefficient

In [10]:
te1 = collect(0:10)

te2 = collect(0:10:100)

bi = kde((te1, te2), npoints = (8, 8))

y = collect(bi.y)

x = collect(bi.x)

z = bi.density

OnePiece.figure.plot_heat_map(z, y, x)

Made /var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.24.853.html.


"/var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece/2022-8-10_21.38.24.853.html"