In [1]:
using Revise
using OnePiece

## apply

In [2]:
function fu(ve1, ve2)
    
    le = sum(ve1)
    
    ri = sum(ve2) 
    
    println("$le & $ri")
    
    le - ri
    
end

fu (generic function with 1 method)

In [3]:
n_ro = 5

n_co = 4

ma = OnePiece.tensor.simulate(n_ro, n_co)

5×4 Matrix{Float64}:
 1.0   6.0  11.0  16.0
 2.0   7.0  12.0  17.0
 3.0   8.0  13.0  18.0
 4.0   9.0  14.0  19.0
 5.0  10.0  15.0  20.0

In [4]:
co = [10^(id - 1) for id in 1:n_co]

4-element Vector{Int64}:
    1
   10
  100
 1000

In [5]:
n_ze = convert(Int64, n_co / 2)

bi = convert(BitVector, [zeros(n_ze); ones(n_co - n_ze)])

4-element BitVector:
 0
 0
 1
 1

In [6]:
OnePiece.tensor_function.apply(co, co, fu)

1111 & 1111


0

In [7]:
OnePiece.tensor_function.apply(bi, co, fu)

11 & 1100


-1089

In [8]:
OnePiece.tensor_function.apply(co, ma, fu)

1111 & 34.0
1111 & 38.0
1111 & 42.0
1111 & 46.0
1111 & 50.0


5-element Vector{Float64}:
 1077.0
 1073.0
 1069.0
 1065.0
 1061.0

In [9]:
OnePiece.tensor_function.apply(bi, ma, fu)

7.0 & 27.0
9.0 & 29.0
11.0 & 31.0
13.0 & 33.0
15.0 & 35.0


5-element Vector{Float64}:
 -20.0
 -20.0
 -20.0
 -20.0
 -20.0

In [10]:
OnePiece.tensor_function.apply(ma, ma, fu)

34.0 & 34.0
38.0 & 34.0
42.0 & 34.0
46.0 & 34.0
50.0 & 34.0
34.0 & 38.0
38.0 & 38.0
42.0 & 38.0
46.0 & 38.0
50.0 & 38.0
34.0 & 42.0
38.0 & 42.0
42.0 & 42.0
46.0 & 42.0
50.0 & 42.0
34.0 & 46.0
38.0 & 46.0
42.0 & 46.0
46.0 & 46.0
50.0 & 46.0
34.0 & 50.0
38.0 & 50.0
42.0 & 50.0
46.0 & 50.0
50.0 & 50.0


5×5 Matrix{Float64}:
  0.0  -4.0  -8.0  -12.0  -16.0
  4.0   0.0  -4.0   -8.0  -12.0
  8.0   4.0   0.0   -4.0   -8.0
 12.0   8.0   4.0    0.0   -4.0
 16.0  12.0   8.0    4.0    0.0

In [11]:
ma2 = [
    1 10 100 1000
    0.001 0.0 1 0.1
]

2×4 Matrix{Float64}:
 1.0    10.0  100.0  1000.0
 0.001   0.0    1.0     0.1

In [12]:
ma1 = [
    0 0 1 1
]

OnePiece.tensor_function.apply(ma1, ma2, fu)

2 & 1111.0
2 & 1.101


1×2 Matrix{Float64}:
 -1109.0  0.899

In [13]:
OnePiece.tensor_function.apply(convert(BitMatrix, ma1), ma2, fu)

11.0 & 1100.0
0.001 & 1.1


1×2 Matrix{Float64}:
 -1089.0  -1.099

In [14]:
OnePiece.tensor_function.apply([
    0 0 1 1
    -1 0 2 3
], ma2, fu)

2 & 1111.0
4 & 1111.0
2 & 1.101
4 & 1.101


2×2 Matrix{Float64}:
 -1109.0  0.899
 -1107.0  2.899