In [1]:
using Revise
using BenchmarkTools

In [2]:
using OnePiece

## apply

In [3]:
n_ro = 5

n_co = 4

n_ze = convert(Int64, n_co / 2)

n_on = n_co - n_ze

2

In [4]:
bi_ = convert(BitVector, [zeros(n_ze); ones(n_on)])

4-element BitVector:
 0
 0
 1
 1

In [5]:
ve = [10^(id - 1) for id in 1:n_co]

4-element Vector{Int64}:
    1
   10
  100
 1000

In [6]:
ma = convert(Matrix, reshape(1:(n_ro * n_co), (n_ro, n_co)))

5×4 Matrix{Int64}:
 1   6  11  16
 2   7  12  17
 3   8  13  18
 4   9  14  19
 5  10  15  20

In [7]:
OnePiece.tensor_function.apply(ve, ve, .-)

4-element Vector{Int64}:
 0
 0
 0
 0

In [8]:
OnePiece.tensor_function.apply(bi_, ve, .-)

2-element Vector{Int64}:
  99
 990

In [9]:
OnePiece.tensor_function.apply(ve, ma, .*)

5-element Vector{Vector{Int64}}:
 [1, 60, 1100, 16000]
 [2, 70, 1200, 17000]
 [3, 80, 1300, 18000]
 [4, 90, 1400, 19000]
 [5, 100, 1500, 20000]

In [10]:
OnePiece.tensor_function.apply(bi_, ma, .+)

5-element Vector{Vector{Int64}}:
 [12, 22]
 [14, 24]
 [16, 26]
 [18, 28]
 [20, 30]

In [11]:
OnePiece.tensor_function.apply(ma, ma, (ro1, ro2) -> minimum([ro1; ro2]))

5×5 Matrix{Int64}:
 1  1  1  1  1
 1  2  2  2  2
 1  2  3  3  3
 1  2  3  4  4
 1  2  3  4  5

In [12]:
for i in [1, 2], j in [10, 20]

    println(i, " ", j)

end

1 10
1 20
2 10
2 20


In [13]:
for i in [1, 2]

    for j in [10, 20]

        println(i, " ", j)

    end

end

1 10
1 20
2 10
2 20


In [14]:
ma2 = [
    1 10 100 1000
    0.001 0.0 1 0.1
]

2×4 Matrix{Float64}:
 1.0    10.0  100.0  1000.0
 0.001   0.0    1.0     0.1

In [15]:
ma1 = [
    0 0 1 1
    -1 0 1 2
]

2×4 Matrix{Int64}:
  0  0  1  1
 -1  0  1  2

In [16]:
OnePiece.tensor_function.apply(ma1, ma2, .+)

2×2 Matrix{Vector{Float64}}:
 [1.0, 10.0, 101.0, 1001.0]  [0.001, 0.0, 2.0, 1.1]
 [0.0, 10.0, 101.0, 1002.0]  [-0.999, 0.0, 2.0, 2.1]

In [17]:
ma1 = convert(
    BitMatrix,
    [
        0 0 1 1
        1 1 0 0
    ],
)

OnePiece.tensor_function.apply(ma1, ma2, .-)

2×2 Matrix{Vector{Float64}}:
 [99.0, 990.0]    [0.999, 0.1]
 [-99.0, -990.0]  [-0.999, -0.1]